import {
  GuidelinesContainer,
  Content,
  Title,
  SubTitle,
  Text,
  Link,
} from "./styles";
import { Wrapper, Container } from "designs/PageLayout";
interface IGuidelinesProps {}

const Guidelines: React.FC<IGuidelinesProps> = props => {
  return (
    <Wrapper>
      <Container>
        <GuidelinesContainer>
          <Title>Affiliate: Guidelines</Title>
          <SubTitle>General</SubTitle>
          <Content>
            <Text>
              You must not use any misleading or deceptive claims in advertising
              copy. You are solely responsible for following all federal, state
              and local laws, regulations and rules regarding advertising
              claims, including but not limited to the Federal Trade
              Commission’s Disclosure Guidelines. You must adhere to all the
              editorial guidelines and search advertising terms and conditions
              set forth by each search engine (Google, Yahoo, MSN; Ask),
              including any updates to those terms in the future. Where search
              engine guidelines and these Terms and Conditions conflict, you
              must follow these Terms and Conditions.
            </Text>
          </Content>
          <SubTitle>Printful Brand Image And Use Of Logo</SubTitle>
          <Content>
            <Text>
              When creating ads, videos, or other online content that publishes
              your affiliate link on websites, Printful’s brand image needs to
              be kept in mind. Sites, where you advertise, cannot be associated
              with content that's vulgar, racist, sexual, or otherwise deemed
              offensive by Printful. You must remove all ads and videos from
              websites deemed offensive within 24 hours of being notified by
              Printful. The Printful logo cannot be altered or changed.
            </Text>
          </Content>
          <SubTitle>Social Media/Social Networking Sites</SubTitle>
          <Content>
            <Text>
              You are prohibited from creating groups or specific web pages in
              social communities to publicize Printful offers.
            </Text>
          </Content>
          <SubTitle>Coupon Websites</SubTitle>
          <Content>
            <Text>
              We encourage affiliates to engage in search engine optimization
              and pay per click activities. The only keywords that we restrict
              affiliates from using are those that include our brand name:
              Printful, The Printful, printful.com, or any variation or
              combination therein (for example, trademarks within a phrase:
              Printful discount, Printful t-shirts, etc.) and any misspelling or
              other confusingly similar variation of Printful brand name. You
              must also not knowingly serve ads that appear in a higher position
              than Printful managed ads. If you are sending paid traffic (PPC,
              PPV, Media Buys) to Printful, it is required to that you send the
              traffic through a landing page or web property first. We do not
              allow direct linking without written approval from the affiliate
              team. These are high performing keywords that publishers are
              permitted to bid on for their search marketing campaigns. Rather
              than provide a full list of keywords, we have highlighted
              best-performing keywords: print on demand; t shirt dropshipping,
              custom t shirts, custom products
            </Text>
          </Content>
          <SubTitle>Limited Use of URL</SubTitle>
          <Content>
            <Text>
              You must not purchase or use domain names containing any Printful
              trademark, including domain names that combine a Printful
              trademark with one or more additional words, letters, numbers, or
              other characters, or domain names containing any misspelling or
              other confusingly similar variation of any Printful trademark.
            </Text>
          </Content>
          <SubTitle>Other Non-Approved Advertising Methods</SubTitle>
          <Content>
            <Text>
              We don't approve self-referrals- you cannot refer yourself to
              Printful and earn commissions from such affiliated customers.
              Clickjacking, linkjacking. typosquating or any sort of domain
              spoofing methods are prohibited. Pixel, cookie stuffing or any
              other type of cookie stuffing without source website visitor's
              knowledge is prohibited. Using traffic generated by pay to read,
              PPC (pay to click), banner exchanges, click exchanges, PPV
              advertising, pop-up/under, or similar methods.
            </Text>
          </Content>
          <Content>
            <Text>
              To read full Affiliate program Terms of Service click{" "}
              <Link>here</Link>.
            </Text>
          </Content>
        </GuidelinesContainer>
        ;
      </Container>
    </Wrapper>
  );
};

export default Guidelines;
