export const GET_ALL_HELP_CENTER_LEVEL1 = "GET_ALL_HELP_CENTER_LEVEL1";
export const GET_ALL_HELP_CENTER_LEVEL1_SUCCESS =
  "GET_ALL_HELP_CENTER_LEVEL1_SUCCESS";

export const GET_ALL_HELP_CENTER_LEVEL2 = "GET_ALL_HELP_CENTER_LEVEL2";
export const GET_ALL_HELP_CENTER_LEVEL2_SUCCESS =
  "GET_ALL_HELP_CENTER_LEVEL2_SUCCESS";

export const GET_ALL_ARTICLE = "GET_ALL_ARTICLE";
export const GET_ALL_ARTICLE_SUCCESS = "GET_ALL_ARTICLE_SUCCESS";

export const SEARCH_ALL_ARTICLE = "SEARCH_ALL_ARTICLE";
export const SEARCH_ALL_ARTICLE_SUCCESS = "SEARCH_ALL_ARTICLE_SUCCESS";

export const ADD_TITLE_LINK = "ADD_TITLE_LINK";
