export const GET_KARAOKE_BY_BOSS = "GET_KARAOKE_BY_BOSS";
export const GET_KARAOKE_BY_BOSS_SUCCESS = "GET_KARAOKE_BY_BOSS_SUCCESS";

export const UPDATE_KARAOKE = "UPDATE_KARAOKE";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const CLEAN_PLACE = "CLEAN_PLACE";
