export const GET_ALL_COMPANY = "GET_ALL_COMPANY";
export const GET_ALL_COMPANY_SUCCESS = "GET_ALL_COMPANY_SUCCESS";

export const GET_ALL_COMPANY_HIGHLIGHT = "GET_ALL_COMPANY_HIGHLIGHT";
export const GET_ALL_COMPANY_HIGHLIGHT_SUCCESS =
  "GET_ALL_COMPANY_HIGHLIGHT_SUCCESS";

export const GET_COMPANY_BY_ID = "GET_COMPANY_BY_ID";
export const GET_COMPANY_SUCCESS = "GET_COMPANY_SUCCESS";

export const CREATE_COMPANY = "CREATE_COMPANY";
export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const SET_PLACE_HIGHLIGHT = "SET_PLACE_HIGHLIGHT";
export const DELETE_COMPANY_BY_ID = "DELETE_COMPANY_BY_ID";
export const DELETE_ALL_COMPANY = "DELETE_ALL_COMPANY";
