export const SUBMITTED = "SUBMITTED";
export const RESET_SUBMITTED = "RESET_SUBMITTED";

export const ACTION_SUCCESS = "ACTION_SUCCESS";
export const RESET_ACTION = "RESET_ACTION";

export const SET_LOADING = "SET_LOADING";
