export const GET_ALL_JOB = "GET_ALL_JOB";
export const GET_ALL_JOB_SUCCESS = "GET_ALL_JOB_SUCCESS";
export const DELETE_JOB = "DELETE_JOB";
export const CREATE_JOB = "CREATE_JOB";
export const UPDATE_JOB = "UPDATE_JOB";

export const GET_RECRUITMENT_VIEWED_USER = "GET_RECRUITMENT_VIEWED_USER";
export const GET_RECRUITMENT_APPLIED_USER = "GET_RECRUITMENT_APPLIED_USER";
export const GET_RECRUITMENT_USER_SUCCESS = "GET_RECRUITMENT_USER_SUCCESS";
