export const GET_ALL_CLOSING_TIME = "GET_ALL_CLOSING_TIME";
export const GET_ALL_CLOSING_TIME_SUCCESS = "GET_ALL_CLOSING_TIME_SUCCESS";

export const CREATE_CLOSING_TIME = "CREATE_CLOSING_TIME";
export const UPDATE_CLOSING_TIME = "UPDATE_CLOSING_TIME";
export const DELETE_CLOSING_TIME_BY_ID = "DELETE_CLOSING_TIME_BY_ID";
