export const GET_ALL_BOOKING = "GET_ALL_BOOKING";
export const GET_ALL_BOOKING_SUCCESS = "GET_ALL_BOOKING_SUCCESS";

export const DELETE_BOOKING = "DELETE_BOOKING";

export const UPDATE_BOOKING = "UPDATE_BOOKING";
export const UPDATE_STATUS_BOOKING = "UPDATE_STATUS_BOOKING";
export const UPDATE_FINISH_BOOKING = "UPDATE_FINISH_BOOKING";
