export const GET_NOTIFICATIONS_BY_USER = "GET_NOTIFICATIONS_BY_USER";
export const GET_NOTIFICATIONS_BY_USER_SUCCESS =
  "GET_NOTIFICATIONS_BY_USER_SUCCESS";

export const GET_NOTIFICATIONS_SETTING = "GET_NOTIFICATIONS_SETTING";
export const GET_NOTIFICATIONS_SETTING_SUCCESS =
  "GET_NOTIFICATIONS_SETTING_SUCCESS";

export const SET_SEEN_FOR_NOTIFY = "SET_SEEN_FOR_NOTIFY";
