export const GET_ALL_CATEGORY_LEVEL1 = "GET_ALL_CATEGORY_LEVEL1";
export const GET_ALL_CATEGORY_LEVEL1_SUCCESS =
    "GET_ALL_CATEGORY_LEVEL1_SUCCESS";

export const CREATE_CATEGORY_LEVEL1 = "CREATE_CATEGORY_LEVEL1";
export const UPDATE_CATEGORY_LEVEL1 = "UPDATE_CATEGORY_LEVEL1";
export const DELETE_CATEGORY_LEVEL1 = "DELETE_CATEGORY_LEVEL1";
