export const GET_ALL_CATEGORY_LEVEL_2 = "GET_ALL_CATEGORY_LEVEL_2";
export const GET_ALL_CATEGORY_LEVEL_2_SUCCESS =
    "GET_ALL_CATEGORY_LEVEL_2_SUCCESS";
export const DELETE_CATEGORY_LEVEL_2 = "DELETE_CATEGORY_LEVEL_2";
export const UPDATE_CATEGORY_LEVEL_2 = "UPDATE_CATEGORY_LEVEL_2";
export const CREATE_CATEGORY_LEVEL_2 = "CREATE_CATEGORY_LEVEL_2";
