export const GET_ALL_JOB_LEVEL = "GET_ALL_JOB_LEVEL";
export const GET_ALL_JOB_LEVEL_SUCCESS = "GET_ALL_JOB_LEVEL_SUCCESS";
export const UPDATE_JOB_LEVEL = "UPDATE_JOB_LEVEL";
export const CREATE_JOB_LEVEL = "CREATE_JOB_LEVEL";
export const DELETE_JOB_LEVEL = "DELETE_JOB_LEVEL";
