export const GET_ALL_JOB_TYPE = "GET_ALL_JOB_TYPE";
export const GET_ALL_JOB_TYPE_SUCCESS = "GET_ALL_JOB_TYPE_SUCCESS";
export const UPDATE_JOB_TYPE = "UPDATE_JOB_TYPE";
export const CREATE_JOB_TYPE = "CREATE_JOB_TYPE";
export const DELETE_JOB_TYPE = "DELETE_JOB_TYPE";
