export const GET_ALL_KEYWORD = "GET_ALL_KEYWORD";
export const GET_ALL_KEYWORD_SUCCESS = "GET_ALL_KEYWORD_SUCCESS";

export const CREATE_KEYWORD = "CREATE_KEYWORD";
export const UPDATE_KEYWORD = "UPDATE_KEYWORD";
export const DELETE_KEYWORD = "DELETE_KEYWORD";
