export const SET_EXTEND_DRAWER = "SET_OPEN_DRAWER";
export const TOGGLE_EXTEND_DRAWER = "TOGGLE_EXTEND_DRAWER";

export const SET_BREADCRUMB = "SET_BREADCRUMB";

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
export const CLEAR_LOADING_TASKS = "CLEAR_LOADING_TASKS";
