export const GET_ALL_NOTIFICATION = "GET_ALL_NOTIFICATION ";
export const GET_ALL_NOTIFICATION_SUCCESS = "GET_ALL_NOTIFICATION_SUCCESS ";

export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION ";
export const UPDATE_NOTIFICATION = "UPDATE_NOTIFICATION ";
export const DELETE_NOTIFICATION_BY_ID = "DELETE_NOTIFICATION_BY_ID ";
