export const GET_ALL_ROOM = "GET_ALL_ROOM";
export const GET_ALL_ROOM_SUCCESS = "GET_ALL_ROOM_SUCCESS";

export const CREATE_ROOM = "CREATE_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM_BY_ID = "DELETE_ROOM_BY_ID";
