export const GET_ALL_MESSAGE = "GET_ALL_MESSAGE ";
export const GET_ALL_MESSAGE_SUCCESS = "GET_ALL_MESSAGE_SUCCESS ";

export const CREATE_MESSAGE = "CREATE_MESSAGE ";
export const UPDATE_MESSAGE = "UPDATE_MESSAGE ";
export const DELETE_MESSAGE_BY_ID = "DELETE_MESSAGE_BY_ID ";
