export const CREATE_USER = "CREATE_USER";

export const CHECK_EXIST_EMAIL = "CHECK_EXIST_EMAIL";
export const CHECK_EXIST_EMAIL_OTHER_PROVIDER =
  "CHECK_EXIST_EMAIL_OTHER_PROVIDER";
export const UPDATE_PASSWORD = "UPDATE_PASSWORD";
