export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";

export const CREATE_CANDIDATE = "CREATE_CANDIDATE";
export const RESET_PASSWORD = "RESET_PASSWORD";

export const GET_CURRENT_USER = "GET_CURRENT_USER";

export const UPDATE_ACCOUNT = "UPDATE_ACCOUNT"
