export const GET_ALL_REQUEST = "GET_ALL_REQUEST";
export const GET_ALL_REQUEST_SUCCESS = "GET_ALL_REQUEST_SUCCESS";

export const GET_REQUEST_BY_ID = "GET_REQUEST_BY_ID";
export const GET_REQUEST_BY_ID_SUCCESS = "GET_REQUEST_BY_ID_SUCCESS";

export const ACCEPT_REQUEST = "ACCEPT_REQUEST";

export const DELETE_REQUEST = "DELETE_REQUEST";
