export const GET_ALL_BENEFIT = "GET_ALL_BENEFIT";
export const GET_ALL_BENEFIT_SUCCESS = "GET_ALL_BENEFIT_SUCCESS";
export const CREATE_BENEFIT = "CREATE_BENEFIT";
export const UPDATE_BENEFIT = "UPDATE_BENEFIT";
export const DELETE_BENEFIT = "DELETE_BENEFIT";
