// DOCUMENT
export const GET_ALL_DOCUMENT = "GET_ALL_DOCUMENT";
export const GET_ALL_DOCUMENT_SUCCESS = "GET_ALL_DOCUMENT_SUCCESS";

export const CREATE_DOCUMENT = "CREATE_DOCUMENT";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const DELETE_DOCUMENT = "DELETE_DOCUMENT";

// BASIC DOCUMENT
export const GET_ALL_BASIC_DOCUMENT = "GET_ALL_BASIC_DOCUMENT";
export const GET_ALL_BASIC_DOCUMENT_SUCCESS = "GET_ALL_BASIC_DOCUMENT_SUCCESS";

export const CREATE_BASIC_DOCUMENT = "CREATE_BASIC_DOCUMENT";
export const UPDATE_BASIC_DOCUMENT = "UPDATE_BASIC_DOCUMENT";
export const DELETE_BASIC_DOCUMENT = "DELETE_BASIC_DOCUMENT";
