export const GET_ALL_TRADE = "GET_ALL_TRADE";
export const GET_ALL_HOT_TRADE = "GET_ALL_HOT_TRADE";
export const GET_ALL_TRADE_SUCCESS = "GET_ALL_TRADE_SUCCESS";
export const GET_ALL_HOT_TRADE_SUCCESS = "GET_ALL_HOT_TRADE_SUCCESS";

export const CREATE_TRADE = "CREATE_TRADE";
export const UPDATE_TRADE = "UPDATE_TRADE";
export const DELETE_TRADE = "DELETE_TRADE";
