export const GET_ALL_PAGES = "GET_ALL_PAGES";
export const GET_ALL_PAGES_SUCCESS = "GET_ALL_PAGES_SUCCESS";

export const UPDATE_PAGE = "UPDATE_PAGE";
export const REMOVE_PAGE = "REMOVE_PAGE";
export const CREATE_PAGE = "CREATE_PAGE";
