export const GET_ROOM_BY_KARAOKE = "GET_ROOM_BY_KARAOKE";
export const GET_ROOM_BY_KARAOKE_SUCCESS = "GET_ROOM_BY_KARAOKE_SUCCESS";

export const CREATE_ROOM = "CREATE_ROOM";
export const UPDATE_ROOM = "UPDATE_ROOM";
export const DELETE_ROOM_BY_ID = "DELETE_ROOM_BY_ID";
