export const GET_ALL_CATEGORY = "GET_ALL_CATEGORY"
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS"

export const GET_ALL_CLIP_ART = "GET_ALL_CLIP_ART"
export const GET_ALL_CLIP_ART_SUCCESS = "GET_ALL_CLIP_ART_SUCCESS"