import { IColor } from "typings";

export const listDetailColors: IColor[] = [
  { hex: "#FFFFFF", name: "White" },
  { hex: "#CDC5C2", name: "Silver" },
  { hex: "#000000", name: "Black" },
  { hex: "#CC6666", name: "Fuzzy Wuzzy" },
  { hex: "#FF2B2B", name: "Orange Red" },
  { hex: "#FF5349", name: "Red Orange" },
  { hex: "#BC5D58", name: "Chestnut" },
  { hex: "#FD5E53", name: "Sunset Orange" },
  { hex: "#FD7C6E", name: "Bittersweet" },
  { hex: "#FDBCB4", name: "Melon" },
  { hex: "#FFA089", name: "Vivid Tangerine" },
  { hex: "#FF6E4A", name: "Outrageous Orange" },
  { hex: "#EA7E5D", name: "Burnt Sienna" },
  { hex: "#B4674D", name: "Brown" },
  { hex: "#DD9475", name: "Copper" },
  { hex: "#FF7F49", name: "Burnt Orange" },
  { hex: "#FF7538", name: "Orange" },
  { hex: "#A5694F", name: "Sepia" },
  { hex: "#FF8243", name: "Mango Tango" },
  { hex: "#FFA474", name: "Atomic Tangerine" },
  { hex: "#CD9575", name: "Antique Brass" },
  { hex: "#9F8170", name: "Beaver" },
  { hex: "#EFCDB8", name: "Desert Sand" },
  { hex: "#DEAA88", name: "Tumbleweed" },
  { hex: "#D68A59", name: "Raw Sienna" },
  { hex: "#FAA76C", name: "Tan" },
  { hex: "#FFCFAB", name: "Peach" },
  { hex: "#FFBD88", name: "Macaroni and Cheese" },
  { hex: "#EFDECD", name: "Almond" },
  { hex: "#FDD9B5", name: "Apricot" },
  { hex: "#FFA343", name: "Neon Carrot" },
  { hex: "#714B23", name: "Raw Umber" },
  { hex: "#DBD7D2", name: "Timberwolf" },
  { hex: "#95918C", name: "Gray" },
  { hex: "#FFAE42", name: "Yellow Orange" },
  { hex: "#E7C697", name: "Gold" },
  { hex: "#8A795D", name: "Shadow" },
  { hex: "#EDD19C", name: "Maize" },
  { hex: "#FAE7B5", name: "Banana Mania" },
  { hex: "#FCD975", name: "Goldenrod" },
  { hex: "#FFCF48", name: "Sunglow" },
  { hex: "#F8D568", name: "Orange Yellow" },
  { hex: "#FDDB6D", name: "Dandelion" },
  { hex: "#FCE883", name: "Yellow" },
  { hex: "#F0E891", name: "Green Yellow" },
  { hex: "#FFF44F", name: "Lemon Yellow" },
  { hex: "#ECEABE", name: "Spring Green" },
  { hex: "#BAB86C", name: "Olive Green" },
  { hex: "#FFFF99", name: "Canary" },
  { hex: "#FFFF66", name: "Unmellow Yellow" },
  { hex: "#FEFE22", name: "Laser Lemon" },
  { hex: "#CEFF1D", name: "Electric Lime" },
  { hex: "#C5E384", name: "Yellow Green" },
  { hex: "#B2EC5D", name: "Inchworm" },
  { hex: "#87A96B", name: "Asparagus" },
  { hex: "#A8E4A0", name: "Granny Smith Apple" },
  { hex: "#76FF7A", name: "Screamin' Green" },
  { hex: "#71BC78", name: "Fern" },
  { hex: "#6DAE81", name: "Forest Green" },
  { hex: "#9FE2BF", name: "Sea Green" },
  { hex: "#AAF0D1", name: "Magic Mint" },
  { hex: "#1CAC78", name: "Green" },
  { hex: "#45CEA2", name: "Shamrock" },
  { hex: "#30BA8F", name: "Mountain Meadow" },
  { hex: "#3BB08F", name: "Jungle Green" },
  { hex: "#1CD3A2", name: "Caribbean Green" },
  { hex: "#17806D", name: "Tropical Rain Forest" },
  { hex: "#158078", name: "Pine Green" },
  { hex: "#1FCECB", name: "Robin's Egg Blue" },
  { hex: "#78DBE2", name: "Aquamarine" },
  { hex: "#77DDE7", name: "Turquoise Blue" },
  { hex: "#18A7B5", name: "Teal Blue" },
  { hex: "#ACE5EE", name: "Blizzard Blue" },
  { hex: "#80DAEB", name: "Sky Blue" },
  { hex: "#1CA9C9", name: "Pacific Blue" },
  { hex: "#414A4C", name: "Outer Space" },
  { hex: "#0D98BA", name: "Blue Green" },
  { hex: "#1DACD6", name: "Cerulean" },
  { hex: "#9ACEEB", name: "Cornflower" },
  { hex: "#1164B4", name: "Green Blue" },
  { hex: "#6699CC", name: "Blue Gray" },
  { hex: "#1974D2", name: "Navy Blue" },
  { hex: "#1A4876", name: "Midnight Blue" },
  { hex: "#2B6CC4", name: "Denim" },
  { hex: "#1F75FE", name: "Blue" },
  { hex: "#C5D0E6", name: "Periwinkle" },
  { hex: "#B0B7C6", name: "Cadet Blue" },
  { hex: "#A2ADD0", name: "Wild Blue Yonder" },
  { hex: "#5D76CB", name: "Indigo" },
  { hex: "#324AB2", name: "Violet Blue" },
  { hex: "#979AAA", name: "Manatee" },
  { hex: "#A2A2D0", name: "Blue Bell" },
  { hex: "#7366BD", name: "Blue Violet" },
  { hex: "#7442C8", name: "Purple Heart" },
  { hex: "#7851A9", name: "Royal Purple" },
  { hex: "#9D81BA", name: "Purple Mountain's Majesty" },
  { hex: "#926EAE", name: "Violet (Purple)" },
  { hex: "#CDA4DE", name: "Wisteria" },
  { hex: "#8F509D", name: "Vivid Violet" },
  { hex: "#FB7EFD", name: "Shocking Pink" },
  { hex: "#C364C5", name: "Fuchsia" },
  { hex: "#FC74FD", name: "Pink Flamingo" },
  { hex: "#8E4585", name: "Plum" },
  { hex: "#FE4EDA", name: "Purple Pizzazz" },
  { hex: "#FF1DCE", name: "Hot Magenta" },
  { hex: "#E6A8D7", name: "Orchid" },
  { hex: "#FF48D0", name: "Razzle Dazzle Rose" },
  { hex: "#EBC7DF", name: "Thistle" },
  { hex: "#C0448F", name: "Red Violet" },
  { hex: "#C54B8C", name: "Mulberry" },
  { hex: "#F664AF", name: "Magenta" },
  { hex: "#FF43A4", name: "Wild Strawberry" },
  { hex: "#DD4492", name: "Cerise" },
  { hex: "#6E5160", name: "Eggplant" },
  { hex: "#FCB4D5", name: "Lavender" },
  { hex: "#FFBCD9", name: "Cotton Candy" },
  { hex: "#FFAACC", name: "Carnation Pink" },
  { hex: "#F75394", name: "Violet Red" },
  { hex: "#E3256B", name: "Razzmatazz" },
  { hex: "#CA3767", name: "Jazzberry Jam" },
  { hex: "#FC89AC", name: "Tickle Me Pink" },
  { hex: "#DE5D83", name: "Blush" },
  { hex: "#FDDDE6", name: "Piggy Pink" },
  { hex: "#F78FA7", name: "Pink Sherbet" },
  { hex: "#C8385A", name: "Maroon" },
  { hex: "#EE204D", name: "Red" },
  { hex: "#EF98AA", name: "Mauvelous" },
  { hex: "#FF496C", name: "Radical Red" },
  { hex: "#FC6C85", name: "Wild Watermelon" },
  { hex: "#FF9BAA", name: "Salmon" },
  { hex: "#FC2847", name: "Scarlet" },
  { hex: "#CB4154", name: "Brick Red" },
  { hex: "#CD4A4C", name: "Mahogany" },
];
