export const SET_LANGUAGE = "SET_LANGUAGE";
export const SET_EXTEND_DRAWER = "SET_OPEN_DRAWER";

export const SET_BREADCRUMB = "SET_BREADCRUMB";
export const SET_COLLAPSE_DRAWER = "SET_COLLAPSE_DRAWER";
export const SET_HOVER_DRAWER = "SET_HOVER_DRAWER";
