export const GET_ALL_KARAOKE = "GET_ALL_KARAOKE";
export const GET_ALL_KARAOKE_HIGHLIGHT = "GET_ALL_KARAOKE_HIGHLIGHT";
export const GET_ALL_KARAOKE_HIGHLIGHT_SUCCESS =
  "GET_ALL_KARAOKE_HIGHLIGHT_SUCCESS";
export const GET_ALL_KARAOKE_SUCCESS = "GET_ALL_KARAOKE_SUCCESS";
export const GET_KARAOKE_BY_ID = "GET_KARAOKE_BY_ID";
export const GET_KARAOKE_SUCCESS = "GET_KARAOKE_SUCCESS";

export const CREATE_KARAOKE = "CREATE_KARAOKE";
export const UPDATE_KARAOKE = "UPDATE_KARAOKE";
export const DELETE_KARAOKE_BY_ID = "DELETE_KARAOKE_BY_ID";
export const DELETE_ALL_KARAOKE = "DELETE_ALL_KARAOKE";

export const CHANGE_COMPANY_TO_KARAOKE = "CHANGE_COMPANY_TO_KARAOKE";
export const CHANGE_KARAOKE_TO_COMPANY = "CHANGE_KARAOKE_TO_COMPANY";
