export const GET_TYPES_BY_CODE = "GET_TYPES_BY_CODE";
export const GET_TYPES_BY_CODE_SUCCESS = "GET_TYPES_BY_CODE_SUCCESS";

export const CREATE_TYPES = "CREATE_TYPES";
export const UPDATE_TYPES = "UPDATE_TYPES";
export const REMOVE_TYPES = "REMOVE_TYPES";
