export const PATH = {
  HOME: "",
  NOT_FOUND: "/not-found",
  ACCOUNT: {
    SELF: "/account",
    LOGIN: "/account/login",
  },
  // Dashboard routes
  OVERVIEW: "/dashboard/overview",
  USER_MANAGEMENT: {
    SELF: "/dashboard/user-management",
    ADD: "/dashboard/user-management/add",
    LIST_USERS: "/dashboard/user-management/list-user",
    ADMINISTRATOR: "/dashboard/user-management/administrator",
    CUSTOMER_CARE_STAFF: "/dashboard/user-management/customer-care-staff",
    SYSTEM_STAFF: "/dashboard/user-management/system-staff",
  },
  BUSINESS_MANAGEMENT: {
    SELF: "/dashboard/business-management",
    REQUEST: "/dashboard/business-management/request",
    REQUEST_DETAIL: "/dashboard/business-management/request-detail/:id",
    COMPANY: "/dashboard/business-management/company",
    COMPANY_DETAIL: "/dashboard/business-management/company/:id",
    KARAOKE: "/dashboard/business-management/karaoke",
    KARAOKE_DETAIL: "/dashboard/business-management/karaoke/:id",
  },
  BOOKING_INFO: {
    SELF: "/dashboard/booking-info",
    COUPON_NEWS: "/dashboard/booking-info/coupon-news",
    COUPON_CODE: "/dashboard/booking-info/coupon-code",
    ROOM: "/dashboard/booking-info/room",
    TRANSACTION: "/dashboard/booking-info/transaction",
  },
  CUSTOMER_CARE: "/dashboard/customer-care",
  MARKER_MANAGEMENT: {
    SELF: "/dashboard/market-management",
    LIST: "/dashboard/market-management/list-product",
    CATEGORY: "/dashboard/market-management/category",
    EXCHANGE_INFO: "/dashboard/market-management/exchange-info",
  },
  MAJOR_DOCS: {
    SELF: "/dashboard/major-docs",
    LIST: "/dashboard/major-docs/list",
    TYPES: "/dashboard/major-docs/types",
    EXCHANGE_HISTORY: "/dashboard/major-docs/history-exchange",
  },
  OTHER_INFO: {
    SELF: "/dashboard/other-info",
    MAILS: "/dashboard/other-info/mails",
    NOTIFICATION: "/dashboard/other-info/notification",
  },
  LOCATION: {
    SELF: "/dashboard/location",
    PROVINCE: "/dashboard/location/province",
    DISTRICT: "/dashboard/location/district",
    WARD: "/dashboard/location/ward",
    STREET: "/dashboard/location/street",
  },
  SYSTEM_SETTING: {
    SELF: "/dashboard/system-setting",
    OUTSTANDING_COMPANY: "/dashboard/system-setting/outstanding-company",
    OUTSTANDING_KARAOKE: "/dashboard/system-setting/outstanding-karaoke",
    OUTSTANDING_STAFFS: "/dashboard/system-setting/outstanding-staffs",
    OUTSTANDING_PRODUCT: "/dashboard/system-setting/outstanding-products",
    OUTSTANDING_DOCUMENTS: "/dashboard/system-setting/outstanding-documents",
    ADS_BY_IMAGE: "/dashboard/system-setting/ads-by-image",
    STATIC_PAGES: "/dashboard/system-setting/static-pages",
  },
};
