export const GET_ALL_PROJECT = "GET_ALL_PROJECT";
export const GET_ALL_PROJECT_SUCCESS = "GET_ALL_PROJECT_SUCCESS";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
