export const GET_ALL_CATEGORY_LV1 = "GET_ALL_CATEGORY_LV1";
export const GET_ALL_CATEGORY_LV1_SUCCESS = "GET_ALL_CATEGORY_LV1_SUCCESS";

export const GET_ALL_CATEGORY_LV2 = "GET_ALL_CATEGORY_LV2";
export const GET_ALL_CATEGORY_LV2_SUCCESS = "GET_ALL_CATEGORY_LV2_SUCCESS";

export const GET_ALL_TAG_MENU = "GET_ALL_TAG_MENU";
export const GET_ALL_TAG_MENU_SUCCESS = "GET_ALL_TAG_MENU_SUCCESS";

export const SET_CATEGORY_LV_1_SELECTED = "SET_CATEGORY_LV_1_SELECTED";
export const SET_TAG_MENU_SELECTED = "SET_TAG_MENU_SELECTED";
export const SET_CATEGORY_LV_2_SELECTED = "SET_CATEGORY_LV_2_SELECTED";
