/* COUPON */

export const GET_PUBLIC_COUPONS = "GET_PUBLIC_COUPONS";
export const GET_PUBLIC_COUPONS_SUCCESS = "GET_PUBLIC_COUPONS_SUCCESS";
export const CREATE_COUPON = "CREATE_COUPON";
export const UPDATE_COUPON = "UPDATE_COUPON";
export const DELETE_COUPON = "DELETE_COUPON";

/* COUPON NEWS */

export const GET_ALL_COUPON_NEWS = "GET_ALL_COUPON_NEWS";
export const GET_ALL_COUPON_NEWS_SUCCESS = "GET_ALL_COUPON_NEWS_SUCCESS";
export const CREATE_COUPON_NEWS = "CREATE_COUPON_NEWS";
export const UPDATE_COUPON_NEWS = "UPDATE_COUPON_NEWS";
export const DELETE_COUPON_NEWS_BY_ID = "DELETE_COUPON_NEWS_BY_ID";
