export const GET_ALL_CARE_STAFF = "GET_ALL_CARE_STAFF";
export const GET_ALL_CARE_STAFF_SUCCESS = "GET_ALL_CARE_STAFF_SUCCESS";

export const GET_CARE_STAFF_BY_ID = "GET_CARE_STAFF_BY_ID";
export const GET_CARE_STAFF_SUCCESS = "GET_CARE_STAFF_SUCCESS";

export const DELETE_CARE_STAFF_BY_ID = "DELETE_CARE_STAFF_BY_ID";
