export const GET_TOKEN = "GET_TOKEN";
export const GET_TOKEN_SUCCESS = "GET_TOKEN_SUCCESS";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const LOG_OUT = "LOG_OUT";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";

export const GET_ACCOUNT_PROFILE = "GET_ACCOUNT_PROFILE";
export const GET_ACCOUNT_PROFILE_SUCCESS = "GET_ACCOUNT_PROFILE_SUCCESS";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
