export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const REMOVE_PROFILE = "REMOVE_PROFILE";
