// Product
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
export const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

// trade
export const GET_ALL_TRADE = "GET_ALL_TRADE";
export const GET_ALL_TRADE_SUCCESS = "GET_ALL_TRADE_SUCCESS";

export const CREATE_TRADE = "CREATE_TRADE";
export const UPDATE_TRADE = "UPDATE_TRADE";
export const DELETE_TRADE = "DELETE_TRADE";
