export const SET_PRODUCT_SCHEMA = "SET_PRODUCT_SCHEMA";
export const SET_IS_CONTINUE_STEP_PREVIEW = "SET_IS_CONTINUE_STEP_PREVIEW";
export const SET_STORE_TEMPLATE_DESIGNED = "SET_STORE_TEMPLATE_DESIGNED";

export const SET_ITEM_ACTIVE = "SET_ITEM_ACTIVE";
