export const GET_ALL_NOTIFY_SETTING = "GET_ALL_NOTIFY_SETTING";
export const GET_ALL_NOTIFY_SETTING_SUCCESS = "GET_ALL_NOTIFY_SETTING_SUCCESS";
export const CREATE_NOTIFY_SETTING = "CREATE_NOTIFY_SETTING";
export const UPDATE_NOTIFY_SETTING = "UPDATE_NOTIFY_SETTING";
export const DELETE_NOTIFY_SETTING = "DELETE_NOTIFY_SETTING";
